### ISSUE TITLE
Add PostgreSQL support as configurable database provider

### ISSUE THREAD

**Issue by nanotaboada** [nanotaboada/Dotnet.Samples.AspNetCore.WebApi#249]
## Problem

The project currently uses SQLite with no option to run a different database engine. The original plan was to add PostgreSQL for Docker/production deployments, but a fixed SQLite-local / PostgreSQL-production split introduces a mixed-environment setup: different engines in dev and prod, which creates subtle behavioral differences that are hard to catch locally.

A better approach is to make the database engine fully configurable, so developers choose one provider and use it consistently — local dev, Docker, and any deployment all run the same engine.

## Proposed Solution

Introduce a `DATABASE_PROVIDER` environment variable that selects the database engine for the entire stack:

- **`DATABASE_PROVIDER=sqlite`** (default): SQLite everywhere. Zero infrastructure required. Works on any machine, including legacy hardware. No Docker needed.
- **`DATABASE_PROVIDER=postgres`**: PostgreSQL everywhere. Requires Docker. Opt-in for developers who want a server-based engine or full production parity.

The default is `sqlite` to keep the barrier to entry as low as possible — clone, run, done.

### 1. Add Npgsql provider

```bash
dotnet add src/.../Dotnet.Samples.AspNetCore.WebApi.csproj package Npgsql.EntityFrameworkCore.PostgreSQL
```

### 2. Update database initialization

Read `DATABASE_PROVIDER` at startup and wire the appropriate EF Core provider:

```csharp
var provider = Environment.GetEnvironmentVariable("DATABASE_PROVIDER") ?? "sqlite";

switch (provider.ToLowerInvariant())
{
    case "postgres":
        options.UseNpgsql(connectionString);
        break;
    default:
        options.UseSqlite(dataSource);
        break;
}
```

### 3. Update `compose.yaml`

Use Docker Compose profiles so the `postgres` service only starts when explicitly requested:

```yaml
services:
  api:
    environment:
      - DATABASE_PROVIDER=${DATABASE_PROVIDER:-sqlite}
      - DATABASE_URL=${DATABASE_URL:-}

  postgres:
    image: postgres:17-alpine
    profiles: [postgres]
    environment:
      POSTGRES_DB: players
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
```

Usage:
```bash
# SQLite (default, no Docker dependency)
docker compose up

# PostgreSQL (opt-in)
DATABASE_PROVIDER=postgres docker compose --profile postgres up
```

### 4. Update `.env.example`

```env
# Database provider: sqlite (default) | postgres
DATABASE_PROVIDER=sqlite

# Required only when DATABASE_PROVIDER=postgres
DATABASE_URL=Host=postgres;Database=players;Username=postgres;Password=your_secure_password_here
POSTGRES_PASSWORD=your_secure_password_here
```

### 5. Add EF Core migrations for PostgreSQL

Run `dotnet ef migrations add` against a PostgreSQL connection to produce provider-specific migrations, or verify the existing SQLite migrations are compatible.

### 6. Update `entrypoint.sh`

Skip the SQLite file-presence check when `DATABASE_PROVIDER=postgres`.

### 7. Add ADR

Add `adr/0014-configurable-database-provider.md`, superseding `adr/0003-use-sqlite-for-data-storage.md`. Document the decision, the two options, and why `sqlite` is the default.

### 8. Update README

Add a "Database" section documenting the two modes and how to switch between them.

## Acceptance Criteria

- [ ] `Npgsql.EntityFrameworkCore.PostgreSQL` added to the project
- [ ] `DATABASE_PROVIDER` env var controls provider selection (`sqlite` default, `postgres` opt-in)
- [ ] `AddDbContextPoolWithSqlite` renamed/replaced to support both providers
- [ ] `docker compose up` works with SQLite, no PostgreSQL container started
- [ ] `DATABASE_PROVIDER=postgres docker compose --profile postgres up` works with PostgreSQL
- [ ] `dotnet run` continues to work with SQLite unchanged
- [ ] `MigrateAsync()` at startup works for both providers
- [ ] All CRUD operations work identically with both providers
- [ ] `.env.example` documents `DATABASE_PROVIDER`, `DATABASE_URL`, and `POSTGRES_PASSWORD`
- [ ] `.env` is git-ignored
- [ ] `adr/0014-configurable-database-provider.md` added, superseding `adr/0003-use-sqlite-for-data-storage.md`
- [ ] `README.md` updated
- [ ] `CHANGELOG.md` updated
- [ ] All existing tests pass

## References

- [Npgsql EF Core provider](https://www.npgsql.org/efcore/)
- [EF Core — Multiple providers](https://learn.microsoft.com/en-us/ef/core/providers/)
- [Docker Compose Profiles](https://docs.docker.com/compose/profiles/)
- Prerequisites: #459 (MigrateAsync at startup — done ✅), #353 (Testcontainers — validates PostgreSQL end-to-end)
- Related: ADR `adr/0003-use-sqlite-for-data-storage.md`
